### ISSUE TITLE
Typo in a variable name

### ISSUE THREAD

**Issue by pyrooka** [Sheepslayer666/checksum_checker#1]
Sir, I think I've found a typo in the code on this line: https://github.com/Sheepslayer666/checksum_checker/blob/05774ff6153fb7af18e1d7015a59f38d75889eee/checksum.py#L20

I suppose you meant to write `sha256_returned` and not `sha256_retunred`.

**Comment by Sheepslayer666** [comment]
Typo fixed!

**Comment by pyrooka** [comment]
I appreciate the quick response! 👌
